### ISSUE TITLE
ISSUE WITH CONFIG FILE

### ISSUE THREAD

**Issue by rabiu-101** [Findomain/Findomain#335]
****I can't use the config.yaml  due to this issue**

**#COMMAND BEING RUN ON KALI TERMINAL**
~$ findomain --target target.com --unique-output /home/kali/result-folders/findomain/file.txt --config /home/kali/Tools/findomain/config.yml

**#OUTPUT**
thread 'main' panicked at src/args.rs:147:18:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction  findomain --target target.com --unique-output  --config 

~$ RUST_BACKTRACE=1 findomain --target target.com --unique-output /home/kali/result-folders/findomain/file.txt --config 

thread 'main' panicked at src/args.rs:147:18:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: findomain::args::get_args
   4: findomain::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
zsh: IOT instruction  RUST_BACKTRACE=1 findomain --target target.com --unique-output  --config**

**Comment by Edu4rdSHL** [comment]
Hello, that looks like a wrong config file. The issue is that it expects an integer but is getting a string.
